# This configuration file is used to build and deploy the app into a 
# GKE cluster using Google Cloud Build.
#
# PREREQUISITES:
# - Cloud Build service account must have role: "Kubernetes Engine Developer"

# USAGE:
# GCP zone and GKE target cluster must be specified as substitutions
# Example invocation:
# `gcloud builds submit --config=cloudbuild.yaml --substitutions=_ZONE=us-central1-b,_CLUSTER=demo-app-staging .`

steps:
- id: 'Write git commit to frontend'
  name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    env
    echo "-----------------"
    tools/insert_git_commit_link.sh
  env:
  - "COMMIT_SHA=$COMMIT_SHA"
  - "SHORT_SHA=$SHORT_SHA"

# steps:
# - id: 'Deploy application to cluster'
#   name: 'gcr.io/k8s-skaffold/skaffold:v0.18.0'
#   entrypoint: 'bash'
#   args: 
#   - '-c'
#   - |
#     gcloud container clusters get-credentials --zone=$_ZONE $_CLUSTER
#     skaffold run -f=skaffold.yaml --default-repo=gcr.io/$PROJECT_ID

# Add more power, and more time, for heavy Skaffold build
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'