apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: adservice
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
            # Lightstep config
            - name: SERVICE_NAME
              value: "adservice"
            - name: HONEYCOMB_API_KEY
              value: "fd7c037a2729ce3ddc9d53449f665aaf"
            - name: HONEYCOMB_TRACES_DATASET
              value: "adservice-traces"
            - name: HONEYCOMB_METRICS_DATASET
              value: "adservice-metrics"
            - name: OTEL_LOG_LEVEL
              value: "error"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 60
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:9555",
                  "-connect-timeout=60s",
                  "-rpc-timeout=60s",
                ]
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 60
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:9555",
                  "-connect-timeout=60s",
                  "-rpc-timeout=60s",
                ]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555