apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-agent
  namespace: opentelemetry-demo
  labels:
    app: opentelemetry
    component: otel-collector-agent
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector-agent
    spec:
      containers:
      - name: otel-collector-agent
        image: otel-collector-agent
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
          - containerPort: 4317
            hostPort: 4317
            protocol: TCP
