name: check-network-config

on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ${{ github.head_ref }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install network checkers
        run: |
          python -m pip install --upgrade pip
          git clone git@github.com:IBM/network-config-analyzer.git ${{ github.workspace }}/network-config-analyzer
          pip install -r  ${{ github.workspace }}/network-config-analyzer/requirements.txt
      - name: Connectivity map
        env:
          GHE_TOKEN: ${{ github.token }}
        run: |
          cd  ${{ github.workspace }}/${{ github.head_ref }}
          python  ${{ github.workspace }}/network-config-analyzer/network-config-analyzer/nca.py --connectivity . --pod_list release/kubernetes-manifests.yaml --ns_list release

