name: Terraform Apply

on:
  push:
    paths:
      - 'Terraform-infra/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
         cli_config_credentials_token: ${{ secrets.GCR_KEY }}

      - name: Terraform Init
        run: |
           pwd
           ls
           terraform init -target=./Terraform-infra/main.tf -target=./Terraform-infra/variables.tf
           
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCR_KEY }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -chdir=Terraform-infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCR_KEY }}
