name: tf-validate-ci
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/tf-validate-ci.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/tf-validate-ci.yml'
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: terraform init & validate
        run: |
          cd terraform/
          terraform init -backend=false
          terraform validate
